export const logInAPI = 'http://localhost:8080/api/nguoidung/dangnhap'
export const signUpAPI = 'http://localhost:8080/api/nguoidung/dangky'
export const allProductAPI = 'http://localhost:8080/api/nguoidung/sanpham'
export const allYardRentedAPI = 'http://localhost:8080/api/nguoidung/sandadat'
export const allYardAPI = 'http://localhost:8080/api/nguoidung/sanbong'